package parser

// TelemetryPacket menyimpan seluruh data dari Forza Data Out (Dash format).
type TelemetryPacket struct {
	IsRaceOn           bool    `json:"isRaceOn"`
	TimestampMs        uint32  `json:"timestampMs"`
	EngineMaxRpm       float32 `json:"engineMaxRpm"`
	EngineIdleRpm      float32 `json:"engineIdleRpm"`
	CurrentEngineRpm   float32 `json:"currentEngineRpm"`
	AccelX             float32 `json:"accelX"`
	AccelY             float32 `json:"accelY"`
	AccelZ             float32 `json:"accelZ"`
	VelX               float32 `json:"velX"`
	VelY               float32 `json:"velY"`
	VelZ               float32 `json:"velZ"`
	Yaw                float32 `json:"yaw"`
	Pitch              float32 `json:"pitch"`
	Roll               float32 `json:"roll"`
	SuspensionFl       float32 `json:"suspensionFl"`
	SuspensionFr       float32 `json:"suspensionFr"`
	SuspensionRl       float32 `json:"suspensionRl"`
	SuspensionRr       float32 `json:"suspensionRr"`
	TireSlipRatioFl    float32 `json:"tireSlipRatioFl"`
	TireSlipRatioFr    float32 `json:"tireSlipRatioFr"`
	TireSlipRatioRl    float32 `json:"tireSlipRatioRl"`
	TireSlipRatioRr    float32 `json:"tireSlipRatioRr"`
	TireSlipAngleFl    float32 `json:"tireSlipAngleFl"`
	TireSlipAngleFr    float32 `json:"tireSlipAngleFr"`
	TireSlipAngleRl    float32 `json:"tireSlipAngleRl"`
	TireSlipAngleRr    float32 `json:"tireSlipAngleRr"`
	CarOrdinal         int32   `json:"carOrdinal"`
	CarClass           int32   `json:"carClass"`
	CarPi              int32   `json:"carPi"`
	DrivetrainType     int32   `json:"drivetrainType"`
	NumCylinders       int32   `json:"numCylinders"`
	PositionX          float32 `json:"positionX"`
	PositionY          float32 `json:"positionY"`
	PositionZ          float32 `json:"positionZ"`
	SpeedMs            float32 `json:"speedMs"`
	Power              float32 `json:"power"`
	Torque             float32 `json:"torque"`
	TireTempFl         float32 `json:"tireTempFl"`
	TireTempFr         float32 `json:"tireTempFr"`
	TireTempRl         float32 `json:"tireTempRl"`
	TireTempRr         float32 `json:"tireTempRr"`
	Boost              float32 `json:"boost"`
	Fuel               float32 `json:"fuel"`
	DistanceTraveled   float32 `json:"distanceTraveled"`
	BestLap            float32 `json:"bestLap"`
	LastLap            float32 `json:"lastLap"`
	CurrentLap         float32 `json:"currentLap"`
	CurrentRaceTime    float32 `json:"currentRaceTime"`
	LapNumber          uint16  `json:"lapNumber"`
	RacePosition       uint8   `json:"racePosition"`
	Throttle           uint8   `json:"throttle"`
	Brake              uint8   `json:"brake"`
	Clutch             uint8   `json:"clutch"`
	Handbrake          uint8   `json:"handbrake"`
	Gear               uint8   `json:"gear"`
	Steer              int8    `json:"steer"`
	DrivingLine        int8    `json:"drivingLine"`
	AiBrakeDiff        int8    `json:"aiBrakeDiff"`
}
